### ISSUE TITLE
buon giorno minetest_game

### ISSUE THREAD

**Issue by Xanthin** [Xanthin/minetest_game#1]
@Emon-Omen would you like to submit your italian translation using the templates?

**Comment by ghost** [comment]
Sure thing, I'll start working on it immediately.

**Comment by ghost** [comment]
The Italian translation is complete, thank you for pointing my attention on this: I'll spread the word on the Italian subforum; and thank you for taking the hassle of adding the Intllib to the minetest_game.

**Comment by Xanthin** [comment]
Thank you, I merged your work in. :) Don't be confused if you see just one commit, I pulled your commits local and squashed the 20 commits into one.
After I "inllib'ed" a lot of minetest mods in the past years it is not that much of a hassle now and I am sure, for you too. Just look how what is done and try it your self. ;)

Oh, and don't misunderstand. This fork is nothing official. It's just the maintenance of what restarted with Adimgar's pull request and work here: #516
Like you can see, it is still open and undecided for more then a year now and to be honest, I didn't understood most of what is talked there. There are several other requests:  #470, #547, https://github.com/minetest/minetest/issues/2270 and some discussion in the forum: https://forum.minetest.net/viewtopic.php?f=5&t=10031.
So probably there is little chance that this will be part of the upstream  one day, but at least: it works. :)

Oh, and maybe you are new with this github thing? Are you using Windows/OS X? Then maybe you want to give [Github Desktop](https://desktop.github.com/) a try. 
I'm not a programmer and know only some little basics learned in the past two years. So I can say, the program is a really good help. You can get more independent from "github in the browser" with it and for example easy create one commit containing changes in multiple files (and also adding textures and sounds!). 

There are also good tutorials in the web that got me started, some of them linked in my [test repo](https://github.com/Xanthin/git_test) and sofar started a [tutorial in the forum](https://forum.minetest.net/viewtopic.php?f=3&t=14262&sid=b5674ec7322fb1f8d27d83cf8f012cb7). Maybe this helps you too. :)
