### ISSUE TITLE
Bom dia, minetest_game!

### ISSUE THREAD

**Issue by Xanthin** [Xanthin/minetest_game#22]
@psergiojr, do you like to PR your work? :)

**Comment by psergiojr** [comment]
I'm just finishing the translations, probably the next commit will be fine to PR ^_^

**Comment by psergiojr** [comment]
Ok, translations done!

(This is the first time I forked something, so I forgot to create a new branch to the translation, sorry)

**Comment by Xanthin** [comment]
Cool. :)

And, no problem. I guess you already read https://github.com/Xanthin/minetest_game/issues/1 and the tutorials I linked there. If you have a question I will also try to help and share what I know, although I'm still not a programmer. ;)

As far as I understand it, creating a new branch in **your** repository is just something helpful for **your own** work flow and doesn't make anything difficult for a pull request to someone else's. For that it doesn't matter. :)
